apiVersion: v1

kind: Service

metadata:

  name: {{ .Release.Namespace }}

  namespace: {{ .Release.Namespace }}

spec:

  type: ClusterIP

  selector:

    app: {{ .Release.Namespace }}

  ports:

    - port: {{ .Values.containerPort }}